dateFormat: "%d.%m.%Y"
rowsForwardForAllRows: 1
slotTitleRowHeight: 25
slotListColumnWidth: 12
slotGroupColumnWidth: 2
slotDateRowHeight: 10
groupTitleRowWidth: 2
itemTitleRowWidth: 40
costLocationColumnWidth: 20
bookingsHeaderWidth:
  default: false
  date: 9
  booking_number: 6
  cost_location: 6
  debit_postingaccount_number: 5
  credit_postingaccount_number: 5
  postingtext: 40
  amount: 15
  currency: 5
  vat: 5
  credit_type: 5

euroFormat : '#0 €' 
euroFormatPrecise : '#,##0.00 €'

bookingsCostlocationColumnHeader : 'cost_location'
bookingsDateColumnHeader : 'date'
bookingsAmountColumnHeader : 'amount'
bookingsDebitBookingsType2 : 'debit_booking_type_2'
bookingsCreditBookingsType2 : 'credit_booking_type_2'

expense_term : "Ausgaben"
income_term : "Einnahmen"

keep_personnel_columns:
  - booking_number
  - date
  - cost_location
  - postingtext
  - amount
  - credit_type
  - debit_postingaccount_number
  - debit_booking_type_1
  - debit_booking_type_2
  - debit_booking_categories
  - credit_postingaccount_number
  - credit_booking_type_1
  - credit_booking_type_2
  - credit_booking_categories
  - transaction_purpose
  - transaction_id_by_customer
  - transactions_purpose
  - realisation

personnel_monthly_sum_columns:
  - '1700'
  - '1705'
  - '1712'
  - '1730'

cosmos_db_url: "https://devintaccountingdb.documents.azure.com:443/"
cosmos_db_id: "WorkingHoursAccounting"

azure_blob_storage_account_name: "devintaccountingftools"
blob_containers:
  templates: "templates"
  financialplanning: "financialplanning"
  financial_reports: "financialreports"
  working_time_reports: "workingtimereports"
  wcc_invoicing: "wccinvoicing"
  od_invoicing: "odinvoicing"

secrets:
  bb_api_key: "bb-api-key"
  bb_authorization: "bb-authorization"
  bb_cookie: "bb-cookie"
  sendgrid_api_key: "sendgrid-api-key"
  cosmos_db_key: "devintaccounting-cosmos-db-key"
  teams_webhook: "teams-webhook-keegan"
  reportrequest_backlink: "reportrequest-backlink"

# ... Add other settings in similar format
