dateFormat: "%d.%m.%Y"
rowsForwardForAllRows: 1
slotTitleRowHeight: 25
slotListColumnWidth: 12
slotGroupColumnWidth: 2
slotDateRowHeight: 10
groupTitleRowWidth: 2
itemTitleRowWidth: 40
costLocationColumnWidth: 20
bookingsHeaderWidth:
  default: false
  date: 9
  booking_number: 6
  cost_location: 6
  debit_postingaccount_number: 5
  credit_postingaccount_number: 5
  postingtext: 40
  amount: 15
  currency: 5
  vat: 5
  credit_type: 5
  debit_booking_type_2: 16
  credit_booking_type_2: 12

euroFormat : '#0 €' 
euroFormatPrecise : '#,##0.00 €'

bookingsCostlocationColumnHeader : 'cost_location'
bookingsDateColumnHeader : 'date'
bookingsAmountColumnHeader : 'amount'
bookingsDebitBookingsType2 : 'debit_booking_type_2'
bookingsCreditBookingsType2 : 'credit_booking_type_2'

expense_term : "Ausgaben"
income_term : "Einnahmen"

keep_personnel_columns:
  - booking_number
  - date
  - cost_location
  - postingtext
  - amount
  - credit_type
  - debit_postingaccount_number
  - debit_booking_type_1
  - debit_booking_type_2
  - debit_booking_categories
  - credit_postingaccount_number
  - credit_booking_type_1
  - credit_booking_type_2
  - credit_booking_categories
  - transaction_purpose
  - transaction_id_by_customer
  - transactions_purpose
  - realisation

skr49_payroll_clearing_accounts:
  '1730' : 'Lohn- und Gehaltsverrechnung'
  '1731' : 'Lohn- und Gehaltsverrechnung nach § 11 Abs. 2 S. 2 EStG für § 4 Abs. 3 EStG'
  '1732' : 'Verbindlichkeiten im Rahmen der sozialen Sicherheit für § 4 Abs. 3 EStG'

skr49_payroll_liabilities_accounts:
  '1700' : 'Verbindlichkeiten aus Lohn- und Kirchensteuer'
  '1705' : 'Verbindlichkeiten im Rahmen der sozialen Sicherheit'
  '1712' : 'Verbindlichkeiten aus Lohn und Gehalt'

skr49_personnel_expenses_non_profit:
  '2550' : 'Anteilige Personalkosten'
  '2551' : 'Löhne und Gehälter'
  '2552' : 'Ehrenamtspauschale'
  '2553' : 'Abgeführte Lohnsteuer'
  '2554' : 'Aufwandsentschädigungen Übungsleiter'
  '2555' : 'Gesetzliche soziale Aufwendungen'
  '2556' : 'Aushilfslöhne'
  '2557' : 'Sachzuwendungen und Dienstleistungen an Arbeitnehmer'
  '2558' : 'Beiträge zur Berufsgenossenschaft'

skr49_personnel_expenses_vat_exempt_purpose:
  '6700' : 'Löhne und Gehälter'
  '6705' : 'Personalkosten Übungsleiter'
  '6710' : 'Aufwandsentschädigung § 3 Nr. 26 EStG'
  '6715' : 'Aushilfslöhne Soziale Abgaben'
  '6750' : 'Gesetzliche soziale Aufwendungen'
  '6751' : 'Beiträge zur Berufsgenossenschaft'

personnel_monthly_sum_columns:
  - '1700'
  - '1705'
  - '1712'
  - '1730'

devint_cost_location_groups:
  '01' : 'allgemeiner ideeller Bereich'
  '12' : 'Zweckbetrieb WCC'
  '13' : 'Zweckbetrieb OD'
  '21' : 'HRM Startup Feb 2022'
  '22' : 'HRM April - Dec 2022'
  '23' : 'HRM 2023 - 2025'
  '24' : 'HRM Support 2023 - 2025'
  '25' : 'HRM 2025 - 2028'

cosmos_db_url: "https://devintaccountingdb.documents.azure.com:443/"
cosmos_db_id: "WorkingHoursAccounting"

azure_blob_storage_account_name: "devintaccountingftools"
blob_containers:
  templates: "templates"
  financialplanning: "financialplanning"
  financial_reports: "financialreports"
  working_time_reports: "workingtimereports"
  wcc_invoicing: "wccinvoicing"
  od_invoicing: "odinvoicing"

secrets:
  bb_api_key: "bb-api-key"
  bb_authorization: "bb-authorization"
  bb_cookie: "bb-cookie"
  sendgrid_api_key: "sendgrid-api-key"
  cosmos_db_key: "devintaccounting-cosmos-db-key"
  teams_webhook: "teams-webhook-keegan"
  reportrequest_backlink: "reportrequest-backlink"

# ... Add other settings in similar format
