dateFormat: "%d.%m.%Y"
titleFont:
  bold: true
  size: 18
rowsForwardForAllRows: 1
slotTitleRowHeight: 25
slotListColumnWidth: 12
slotGroupColumnWidth: 2
slotTitleFont:
  bold: true
  size: 10
slotTitleAlignment:
  horizontal: 'center'
  vertical: 'top'
  wrap_text: true
slotDateFont:
  bold: false
  size: 6
  color: '333333'
slotDateRowHeight: 10
groupTitleRowWidth: 2
itemTitleRowWidth: 40
costLocationColumnWidth: 20
bookingsHeaderWidth:
  default: false
  date: 9
  booking_number: 6
  cost_location: 6
  debit_postingaccount_number: 5
  credit_postingaccount_number: 5
  postingtext: 40
  amount: 15
  currency: 5
  vat: 5
  credit_type: 5
depth1Font:
  name: 'Cambria'
  bold: true
  size: 12

azure_blob_storage_account_name: "devintaccounting"
cosmos_db_url: "https://devintaccountingdb.documents.azure.com:443/"
cosmos_db_id: "WorkingHoursAccounting"

blob_containers:
  templates: "templates"
  financialplanning: "financialplanning"
  financial_reports: "financialreports"
  working_time_reports: "workingtimereports"
  wcc_invoicing: "wccinvoicing"
  od_invoicing: "odinvoicing"

secrets:
  bb_api_key: "bb-api-key"
  bb_authorization: "bb-authorization"
  bb_cookie: "bb-cookie"
  sendgrid_api_key: "sendgrid-api-key"
  cosmos_db_key: "devintaccounting-cosmos-db-key"
  teams_webhook: "teams-webhook-keegan"
  reportrequest_backlink: "reportrequest-backlink"

# ... Add other settings in similar format
