# devint_settings.py
from openpyxl import styles

settings = {
    'dateFormat': "%d.%m.%Y",
    'titleFont': styles.Font(bold=True, size=18),
    'rowsForwardForAllRows': 1,
    'slotTitleRowHeight': 25,
    'slotListColumnWidth': 12,
    'slotGroupColumnWidth': 2,
    'slotTitleFont': styles.Font(bold=True, size=10),
    'slotTitleAlignment': styles.Alignment(horizontal='center', vertical='top', wrap_text=True),
    'slotDateFont': styles.Font(bold=False, size=6, color='333333'),
    'slotDateRowHeight': 10,
    'groupTitleRowWidth': 2,
    'itemTitleRowWidth': 40,
    'costLocationColumnWidth': 20,
    'bookingsHeaderWidth': {
        'default': False,
        'date': 9,
        'booking_number': 6,
        'cost_location': 6,
        'debit_postingaccount_number': 5,
        'credit_postingaccount_number': 5,
        'postingtext': 40,
        'amount': 15,
        'currency': 5,
        'vat': 5,
        'credit_type': 5,
    },
    'depth1Font': styles.Font(name='Cambria', bold=True, size=12, ),
    'depth2Font': styles.Font(name='Cambria', bold=True, size=14, ),
    'depth3Font': styles.Font(name='Cambria', bold=True, size=16, ),
    'depth4Font': styles.Font(name='Cambria', bold=True, size=18, ),
    'depth5Font': styles.Font(name='Cambria', bold=True, size=20, ),
    'level0Fill': styles.PatternFill(fill_type='solid', start_color='85bfe6', end_color='85bfe6'),
    'level1Fill': styles.PatternFill(fill_type='solid', start_color='96c9eb', end_color='96c9eb'),
    'level2Fill': styles.PatternFill(fill_type='solid', start_color='a7d4f2', end_color='a7d4f2'),
    'level3Fill': styles.PatternFill(fill_type='solid', start_color='b5dbf5', end_color='b5dbf5'),
    'listingsHeaderFill': styles.PatternFill(fill_type='solid', start_color='bee0ec', end_color='bee0ec'),
    'euroFormat': '#0 €',
    'euroFormatPrecise': '#,##0.00 €',
    'bookingsCostlocationColumnHeader': 'cost_location',
    'bookingsDateColumnHeader': 'date',
    'bookingsAmountColumnHeader': 'amount',
    'bookingsDebitBookingsType2': 'debit_booking_type_2',
    'bookingsCreditBookingsType2': 'credit_booking_type_2',
}
