name: Azure Functions CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: 'Install Azure Functions Core Tools'
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true

    - name: 'Deploy to Azure Function App'
      uses: Azure/functions-action@v1
      with:
        app-name: 'devintaccountingftools'
        package: '.'
